# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/daver/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake

# The command to remove a file.
RM = /Users/daver/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/daver/Desktop/HPC_Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/daver/Desktop/HPC_Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/Users/daver/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Users/daver/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/daver/Desktop/HPC_Project/CMakeFiles /Users/daver/Desktop/HPC_Project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/daver/Desktop/HPC_Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HPC_Project

# Build rule for target.
HPC_Project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HPC_Project
.PHONY : HPC_Project

# fast build rule for target.
HPC_Project/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/build
.PHONY : HPC_Project/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/main.cpp.s
.PHONY : main.cpp.s

trial.o: trial.cpp.o
.PHONY : trial.o

# target to build an object file
trial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/trial.cpp.o
.PHONY : trial.cpp.o

trial.i: trial.cpp.i
.PHONY : trial.i

# target to preprocess a source file
trial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/trial.cpp.i
.PHONY : trial.cpp.i

trial.s: trial.cpp.s
.PHONY : trial.s

# target to generate assembly for a file
trial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/trial.cpp.s
.PHONY : trial.cpp.s

utils/display_functions.o: utils/display_functions.cpp.o
.PHONY : utils/display_functions.o

# target to build an object file
utils/display_functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/utils/display_functions.cpp.o
.PHONY : utils/display_functions.cpp.o

utils/display_functions.i: utils/display_functions.cpp.i
.PHONY : utils/display_functions.i

# target to preprocess a source file
utils/display_functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/utils/display_functions.cpp.i
.PHONY : utils/display_functions.cpp.i

utils/display_functions.s: utils/display_functions.cpp.s
.PHONY : utils/display_functions.s

# target to generate assembly for a file
utils/display_functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/utils/display_functions.cpp.s
.PHONY : utils/display_functions.cpp.s

utils/filter_functions.o: utils/filter_functions.cpp.o
.PHONY : utils/filter_functions.o

# target to build an object file
utils/filter_functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/utils/filter_functions.cpp.o
.PHONY : utils/filter_functions.cpp.o

utils/filter_functions.i: utils/filter_functions.cpp.i
.PHONY : utils/filter_functions.i

# target to preprocess a source file
utils/filter_functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/utils/filter_functions.cpp.i
.PHONY : utils/filter_functions.cpp.i

utils/filter_functions.s: utils/filter_functions.cpp.s
.PHONY : utils/filter_functions.s

# target to generate assembly for a file
utils/filter_functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/utils/filter_functions.cpp.s
.PHONY : utils/filter_functions.cpp.s

utils/parallel_dependent_codes.o: utils/parallel_dependent_codes.cpp.o
.PHONY : utils/parallel_dependent_codes.o

# target to build an object file
utils/parallel_dependent_codes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/utils/parallel_dependent_codes.cpp.o
.PHONY : utils/parallel_dependent_codes.cpp.o

utils/parallel_dependent_codes.i: utils/parallel_dependent_codes.cpp.i
.PHONY : utils/parallel_dependent_codes.i

# target to preprocess a source file
utils/parallel_dependent_codes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/utils/parallel_dependent_codes.cpp.i
.PHONY : utils/parallel_dependent_codes.cpp.i

utils/parallel_dependent_codes.s: utils/parallel_dependent_codes.cpp.s
.PHONY : utils/parallel_dependent_codes.s

# target to generate assembly for a file
utils/parallel_dependent_codes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/utils/parallel_dependent_codes.cpp.s
.PHONY : utils/parallel_dependent_codes.cpp.s

utils/parallel_independent_codes.o: utils/parallel_independent_codes.cpp.o
.PHONY : utils/parallel_independent_codes.o

# target to build an object file
utils/parallel_independent_codes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/utils/parallel_independent_codes.cpp.o
.PHONY : utils/parallel_independent_codes.cpp.o

utils/parallel_independent_codes.i: utils/parallel_independent_codes.cpp.i
.PHONY : utils/parallel_independent_codes.i

# target to preprocess a source file
utils/parallel_independent_codes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/utils/parallel_independent_codes.cpp.i
.PHONY : utils/parallel_independent_codes.cpp.i

utils/parallel_independent_codes.s: utils/parallel_independent_codes.cpp.s
.PHONY : utils/parallel_independent_codes.s

# target to generate assembly for a file
utils/parallel_independent_codes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/utils/parallel_independent_codes.cpp.s
.PHONY : utils/parallel_independent_codes.cpp.s

utils/serial_codes.o: utils/serial_codes.cpp.o
.PHONY : utils/serial_codes.o

# target to build an object file
utils/serial_codes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/utils/serial_codes.cpp.o
.PHONY : utils/serial_codes.cpp.o

utils/serial_codes.i: utils/serial_codes.cpp.i
.PHONY : utils/serial_codes.i

# target to preprocess a source file
utils/serial_codes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/utils/serial_codes.cpp.i
.PHONY : utils/serial_codes.cpp.i

utils/serial_codes.s: utils/serial_codes.cpp.s
.PHONY : utils/serial_codes.s

# target to generate assembly for a file
utils/serial_codes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HPC_Project.dir/build.make CMakeFiles/HPC_Project.dir/utils/serial_codes.cpp.s
.PHONY : utils/serial_codes.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... HPC_Project"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... trial.o"
	@echo "... trial.i"
	@echo "... trial.s"
	@echo "... utils/display_functions.o"
	@echo "... utils/display_functions.i"
	@echo "... utils/display_functions.s"
	@echo "... utils/filter_functions.o"
	@echo "... utils/filter_functions.i"
	@echo "... utils/filter_functions.s"
	@echo "... utils/parallel_dependent_codes.o"
	@echo "... utils/parallel_dependent_codes.i"
	@echo "... utils/parallel_dependent_codes.s"
	@echo "... utils/parallel_independent_codes.o"
	@echo "... utils/parallel_independent_codes.i"
	@echo "... utils/parallel_independent_codes.s"
	@echo "... utils/serial_codes.o"
	@echo "... utils/serial_codes.i"
	@echo "... utils/serial_codes.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

